dist: xenial
language: go
go: 1.12.x
sudo: false
git:
  depth: 1
before_script:
  - make test
deploy:
  - provider: releases
    name: "$TRAVIS_TAG"
    body: "**Release Notes:** Coming soon"
    api_key:
      secure: TAeazJHm6X4xvdwlFsQxS3qmMGHJ5Tu1a30+2kmiOMQBrcTrbPKun/8aCAV8+PxtaXaLsZ59IZcHBmB/Lag4zNM3HC+3e/7HFJwr7cYE7mKtRG5+2xssA6IpEq5yAqvkDqgNLkliCUtNhC/h8PrWv1G+7rOu9ejjsgD/a8FLFWipZqeuFWeaPAHyTbc+NajtImfL2ussnugWgBCxuy5914mzGdwEVq0ttdmvlTru+U3ltQMI8TGYCVApqKYPNocv0OPDV39Xm5zf+VJwiLAMFWbVQeqJ3LNcMHby8fDoJ266POffGApmyMsZs1Zm0t29romc6BdLzDN/K6HJ8cFESWWVNDoZn922KJrgACT01jOiMzRqXrh81VeXGA0yPJcCzeXX9y099Fh92wxYuzd29fS1jDO4RryQ1q6rDDYejAPEbDvdCgDlhMfBAovWA2iqPAuBm+M3QERLbMKbhamugrYsKW9ijKFU4tW4QLcoXA1B34hL1XRNzqukvtc1lpnEgFfB//d7F4WNXr1ac+r7jozm4OdUfhbho34p00gNOJwMAMseynML6eIiWstfTdDID1nGrnvpqoeQx1Vdj7Z5u+w9LM1ZtOkdnPcbROcLHEeVQ/FR4JGAEAyLjL2myGvnPfNJlTCKU9V0kdJYCHa/bT44BAHUau9GFUkYzvZFrMY=
    skip_cleanup: true
    file_glob: true
    file: out/*
    prerelease: true
    draft: false
    on:
      branch: master
      repo: james-d-elliott/go-hekatechkbkp
      tags: true
      condition: "$TRAVIS_TAG =~ ^v"