dist: xenial
language: go
go: 1.12.x
sudo: false
git:
  depth: 1
before_script:
  - make test
  - |
    export PRERELEASE=false
    if [[ ${TRAVIS_TAG} =~ ^(0|[1-9]+)\.(0|[1-9]+)\.(0|[1-9]+)(-[0-9a-zA-Z\.]+)?(\+[0-9a-zA-Z]+)?$ ]]; then
      export SEMVER=${TRAVIS_TAG}
      if [[ $TRAVIS_TAG == *"-alpha"* ]] || [[ $TRAVIS_TAG == *"-beta"* ]]; then
        export PRERELEASE=true
      fi
    else
      export SEMVER=0
      export test=test
    fi
deploy:
  - provider: releases
    name: "$TRAVIS_TAG"
    body: "**Release Notes:** Coming soon"
    api_key:
      secure: gohVV8QDSg+lg97IOcQtoF0sngMMbjQ7SsvzyEx6RJH4nu6GQzaV8QU1f4tG79f3P6iKW9FynRIZRPD/IqicEtvVOSD1wtgAZUKTD0BdtFTTXrEjaU2NrM7/nGIcVmx09Qphf8eynPyOiHSME8/5dYk5HUSevczpnoVKfYhCvZpEndI+9TbvHY6PMXCGVMbBDSiL2AvJUXAsQHntaiyzILd8fJEfZyZv6b50l+jTOC91IeHZygDuI+VL/pcDVFYrZVAf4HTma8JlAzI0p7VsApXeL4SJ2FEdLXZjhpbIRHPh75Q9GK2njRwGUcYr8ynuoGdIJDWFNQuNeQg+eAWA2sHRYzTodZPqoYAsqy4IrnN+3vGo60mHWgkG94fi8qIdH/C6RtqKaHZNAPtkqtPeP5yVmptlywc7fkE8Mcps7MbyPKQKONWW1wLtIDgcccc6+ZZlONKgOuppjcerwf47lAoDIq8BYPUHrSzwd1FecPn3YA/2MjUakDeSo/0WtsKAedZa6PgoXF4Z4io4wjT8P7jPwNnQz1sF/GyoPYwEth8qJ81bK95js+YUgGhSs/xQrmMY8jVLy1wGfRRkM0dWG7Uuid0Jz/TuNZj9xFH3JO6pv8AxXM3Ml746OES31U6ent3HnovcqmP1wHeWlu+NyHAh8ZWSZSqp4iaz4HnAyqc=
    skip_cleanup: true
    file_glob: true
    file: out/*
    prerelease: $PRERELEASE
    draft: false
    on:
      branch: master
      repo: james-d-elliott/go-hekatechkbkp
      tags: true
      condition: "$SEMVER != 0"